version: '3.3'

services:
  landing:
    build:
      dockerfile: ./Dockerfile.landing
      context: .
    restart: always
    ports:
      - "83:3000"
  app:
    build:
      dockerfile: ./Dockerfile.app
      context: .
    restart: always
    ports:
      - "89:3000"
  monitor:
    build:
      dockerfile: ./Dockerfile.monitor
      context: .
    restart: always
    environment:
      - NX_MONITOR_BASE_URL=https://beta.ingl.io
    ports:
      - "88:8080"
